### ISSUE TITLE
Add an endpoint for just the rate

### ISSUE THREAD

**Issue by bitkarrot** [bitkarrot/satsconverter#12]
Add an endpoint to the flask server which will return just the BTC/USD, or other pair rate as a single value. 

e.g. "/rate?btcusd"  will return the value of the exchange rate already parsed for other applications to use

**Comment by sudheersingampalli** [comment]
Hi @bitkarrot -- i created a PR for this issue. Please go review it and let me know if any changes are required.
Thanks :)

**Comment by bitkarrot** [comment]
Thank you! @sudheersingampalli , we merged this now :)
