### ISSUE TITLE
Add commas to number format

### ISSUE THREAD

**Issue by bitkarrot** [bitkarrot/satsconverter#2]
Example: 1000000 sats should have the format with commas so its easier to read - 1,000,000
Same for fiat - 28416.77 should be reformatted to 28,416.77

**Comment by charanravi-online** [comment]
Hi @bitkarrot.
I tried to implement this format function but I was unable to understand where you're actually getting the data.
I'm new to this. Could you please let me know where I can look for. 
I'm trying to look for the part where the data is being fetched via the API so I can assign it to a variable and then format it before printing it.
Please let me know if this is a good approach, or any other approach should be taken into consideration.

**Comment by charanravi-online** [comment]
@bitkarrot 
Just an update,
I added in the formats and it looks like this,
![image](https://user-images.githubusercontent.com/84191978/232271446-c239c30c-1454-4439-9600-e61d79bbbf65.png)

But what I've noticed was that when the site is loaded for the first time, the format is not added to the converted value, which is there by default. I personally feel if format can be set even when the site is loaded with a default value, it would be nice.
Here's the screenshot for that,
![Screenshot from 2023-04-16 10-29-16](https://user-images.githubusercontent.com/84191978/232271979-3fa7b32d-a501-4224-af62-da0e7bc63b0a.png)
I am trying to figure out and will update once this is fixed.

**Comment by charanravi-online** [comment]
@bitkarrot since the code is merged, can this issue be closed?

**Comment by bitkarrot** [comment]
> @bitkarrot since the code is merged, can this issue be closed?
> 
> #5

Yes absolutely! Would you also be interested in joining our developer chat room for bitcoin.org.hk? If so, drop me your telegram handle and i'll add you

**Comment by charanravi-online** [comment]
sure, it's t.me/charan_ravi
closing this issue.

**Comment by bitkarrot** [comment]
Closed
