### ISSUE TITLE
sats conversion from fiat to btc is rounding instead of exact. 

### ISSUE THREAD

**Issue by bitkarrot** [bitkarrot/satsconverter#9]
if type in 0.001 BTC get 28.454 USD

however, if type in 25.00 USD, get 0.001 BTC from rounding up. 

so the reverse conversion is inaccurate.

The amount in BTC should never be rounded up

the BTC decimal needs to be at least 8 digits

<img width="692" alt="Screenshot 2023-05-03 at 10 14 22 AM" src="https://user-images.githubusercontent.com/73979971/235993649-98ea8d7e-c273-4d85-b742-e97856b701aa.png">
<img width="717" alt="Screenshot 2023-05-03 at 10 14 33 AM" src="https://user-images.githubusercontent.com/73979971/235993667-1e022f87-0563-4008-afde-baa7a1b00d6d.png">

**Comment by bitkarrot** [comment]
Looks good - @charanravi-online please do make a PR, I'll review the deploy from there as well. Thank you!

**Comment by charanravi-online** [comment]
created a PR for this fix - https://github.com/bitkarrot/satsconverter/pull/10

**Comment by bitkarrot** [comment]
Closed as merged
